// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
)

type IndexState struct {
	Singleton  int64
	Generation int64
}

type IndexedDocument struct {
	Text      string
	SessionID string
	Seq       string
	Type      string
	Time      string
	Surface   string
}

type IndexedSession struct {
	ID              string
	Version         int64
	CreatedAt       int64
	Cwd             sql.NullString
	ParentSession   sql.NullString
	SeedLength      sql.NullInt64
	Origin          string
	DelegationDepth sql.NullInt64
	AgentPreset     sql.NullString
	Live            int64
	Persisted       int64
	SourceRevision  string
	Generation      int64
}
