// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbsql

import (
	"context"
	"database/sql"
)

const deleteIndexedDocuments = `-- name: DeleteIndexedDocuments :exec
DELETE FROM indexed_documents WHERE session_id = ?
`

func (q *Queries) DeleteIndexedDocuments(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteIndexedDocuments, sessionID)
	return err
}

const deleteIndexedSession = `-- name: DeleteIndexedSession :exec
DELETE FROM indexed_sessions WHERE id = ?
`

func (q *Queries) DeleteIndexedSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIndexedSession, id)
	return err
}

const getIndexGeneration = `-- name: GetIndexGeneration :one
SELECT generation FROM index_state WHERE singleton = 1
`

func (q *Queries) GetIndexGeneration(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIndexGeneration)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getIndexedSession = `-- name: GetIndexedSession :one
SELECT id, version, created_at, cwd, parent_session, seed_length, origin,
       delegation_depth, agent_preset, live, persisted, source_revision, generation
FROM indexed_sessions
WHERE id = ?
`

func (q *Queries) GetIndexedSession(ctx context.Context, id string) (IndexedSession, error) {
	row := q.db.QueryRowContext(ctx, getIndexedSession, id)
	var i IndexedSession
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.Cwd,
		&i.ParentSession,
		&i.SeedLength,
		&i.Origin,
		&i.DelegationDepth,
		&i.AgentPreset,
		&i.Live,
		&i.Persisted,
		&i.SourceRevision,
		&i.Generation,
	)
	return i, err
}

const incrementIndexGeneration = `-- name: IncrementIndexGeneration :exec
UPDATE index_state SET generation = generation + 1 WHERE singleton = 1
`

func (q *Queries) IncrementIndexGeneration(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementIndexGeneration)
	return err
}

const insertIndexedDocument = `-- name: InsertIndexedDocument :exec
INSERT INTO indexed_documents (text, session_id, seq, type, time, surface)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertIndexedDocumentParams struct {
	Text      string
	SessionID string
	Seq       string
	Type      string
	Time      string
	Surface   string
}

func (q *Queries) InsertIndexedDocument(ctx context.Context, arg InsertIndexedDocumentParams) error {
	_, err := q.db.ExecContext(ctx, insertIndexedDocument,
		arg.Text,
		arg.SessionID,
		arg.Seq,
		arg.Type,
		arg.Time,
		arg.Surface,
	)
	return err
}

const listIndexedSessions = `-- name: ListIndexedSessions :many
SELECT id, version, created_at, cwd, parent_session, seed_length, origin,
       delegation_depth, agent_preset, live, persisted, source_revision, generation
FROM indexed_sessions
`

func (q *Queries) ListIndexedSessions(ctx context.Context) ([]IndexedSession, error) {
	rows, err := q.db.QueryContext(ctx, listIndexedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexedSession{}
	for rows.Next() {
		var i IndexedSession
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.Cwd,
			&i.ParentSession,
			&i.SeedLength,
			&i.Origin,
			&i.DelegationDepth,
			&i.AgentPreset,
			&i.Live,
			&i.Persisted,
			&i.SourceRevision,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIndexedSession = `-- name: UpsertIndexedSession :exec
INSERT INTO indexed_sessions (
    id, version, created_at, cwd, parent_session, seed_length, origin,
    delegation_depth, agent_preset, live, persisted, source_revision, generation
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    version = excluded.version,
    created_at = excluded.created_at,
    cwd = excluded.cwd,
    parent_session = excluded.parent_session,
    seed_length = excluded.seed_length,
    origin = excluded.origin,
    delegation_depth = excluded.delegation_depth,
    agent_preset = excluded.agent_preset,
    live = excluded.live,
    persisted = excluded.persisted,
    source_revision = excluded.source_revision,
    generation = excluded.generation
`

type UpsertIndexedSessionParams struct {
	ID              string
	Version         int64
	CreatedAt       int64
	Cwd             sql.NullString
	ParentSession   sql.NullString
	SeedLength      sql.NullInt64
	Origin          string
	DelegationDepth sql.NullInt64
	AgentPreset     sql.NullString
	Live            int64
	Persisted       int64
	SourceRevision  string
	Generation      int64
}

func (q *Queries) UpsertIndexedSession(ctx context.Context, arg UpsertIndexedSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertIndexedSession,
		arg.ID,
		arg.Version,
		arg.CreatedAt,
		arg.Cwd,
		arg.ParentSession,
		arg.SeedLength,
		arg.Origin,
		arg.DelegationDepth,
		arg.AgentPreset,
		arg.Live,
		arg.Persisted,
		arg.SourceRevision,
		arg.Generation,
	)
	return err
}
