// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
)

type SessionProjectionCheckpoint struct {
	SessionID string
	CreatedAt int64
	Cwd       sql.NullString
	RowsJson  []byte
}
