// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbsql

import (
	"context"
	"database/sql"
)

const listCheckpoints = `-- name: ListCheckpoints :many
SELECT session_id, created_at, cwd, rows_json
FROM session_projection_checkpoints
ORDER BY session_id
`

func (q *Queries) ListCheckpoints(ctx context.Context) ([]SessionProjectionCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionProjectionCheckpoint{}
	for rows.Next() {
		var i SessionProjectionCheckpoint
		if err := rows.Scan(
			&i.SessionID,
			&i.CreatedAt,
			&i.Cwd,
			&i.RowsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCheckpoint = `-- name: ReplaceCheckpoint :exec
INSERT INTO session_projection_checkpoints (
    session_id,
    created_at,
    cwd,
    rows_json
) VALUES (?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
    created_at = excluded.created_at,
    cwd = excluded.cwd,
    rows_json = excluded.rows_json
`

type ReplaceCheckpointParams struct {
	SessionID string
	CreatedAt int64
	Cwd       sql.NullString
	RowsJson  []byte
}

func (q *Queries) ReplaceCheckpoint(ctx context.Context, arg ReplaceCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, replaceCheckpoint,
		arg.SessionID,
		arg.CreatedAt,
		arg.Cwd,
		arg.RowsJson,
	)
	return err
}
