// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbsql

import (
	"context"
	"database/sql"
)

const deleteEventsFrom = `-- name: DeleteEventsFrom :exec
DELETE FROM events WHERE session_id = ? AND seq >= ?
`

type DeleteEventsFromParams struct {
	SessionID string
	Seq       int64
}

func (q *Queries) DeleteEventsFrom(ctx context.Context, arg DeleteEventsFromParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventsFrom, arg.SessionID, arg.Seq)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, version, created_at, cwd, parent_session, seed_length, origin,
       delegation_depth, agent_preset, incarnation, revision
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.CreatedAt,
		&i.Cwd,
		&i.ParentSession,
		&i.SeedLength,
		&i.Origin,
		&i.DelegationDepth,
		&i.AgentPreset,
		&i.Incarnation,
		&i.Revision,
	)
	return i, err
}

const getSessionRevision = `-- name: GetSessionRevision :one
SELECT incarnation, revision FROM sessions WHERE id = ?
`

type GetSessionRevisionRow struct {
	Incarnation string
	Revision    int64
}

func (q *Queries) GetSessionRevision(ctx context.Context, id string) (GetSessionRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionRevision, id)
	var i GetSessionRevisionRow
	err := row.Scan(&i.Incarnation, &i.Revision)
	return i, err
}

const getStoreIdentity = `-- name: GetStoreIdentity :one
SELECT store_id FROM persistence_state WHERE singleton = 1
`

func (q *Queries) GetStoreIdentity(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getStoreIdentity)
	var store_id string
	err := row.Scan(&store_id)
	return store_id, err
}

const incrementRevision = `-- name: IncrementRevision :execrows
UPDATE sessions SET revision = revision + 1 WHERE id = ?
`

func (q *Queries) IncrementRevision(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementRevision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    session_id, seq, type, time, data, source_event_seqs, surface_op, ignorable
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	SessionID       string
	Seq             int64
	Type            string
	Time            int64
	Data            string
	SourceEventSeqs sql.NullString
	SurfaceOp       sql.NullString
	Ignorable       sql.NullInt64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.SessionID,
		arg.Seq,
		arg.Type,
		arg.Time,
		arg.Data,
		arg.SourceEventSeqs,
		arg.SurfaceOp,
		arg.Ignorable,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (
    id, version, created_at, cwd, parent_session, seed_length, origin,
    delegation_depth, agent_preset, incarnation, revision
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
`

type InsertSessionParams struct {
	ID              string
	Version         int64
	CreatedAt       int64
	Cwd             sql.NullString
	ParentSession   sql.NullString
	SeedLength      sql.NullInt64
	Origin          sql.NullString
	DelegationDepth sql.NullInt64
	AgentPreset     sql.NullString
	Incarnation     string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.Version,
		arg.CreatedAt,
		arg.Cwd,
		arg.ParentSession,
		arg.SeedLength,
		arg.Origin,
		arg.DelegationDepth,
		arg.AgentPreset,
		arg.Incarnation,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT seq, type, time, data, source_event_seqs, surface_op, ignorable
FROM events
WHERE session_id = ?
ORDER BY seq
`

type ListEventsRow struct {
	Seq             int64
	Type            string
	Time            int64
	Data            string
	SourceEventSeqs sql.NullString
	SurfaceOp       sql.NullString
	Ignorable       sql.NullInt64
}

func (q *Queries) ListEvents(ctx context.Context, sessionID string) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.Time,
			&i.Data,
			&i.SourceEventSeqs,
			&i.SurfaceOp,
			&i.Ignorable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBefore = `-- name: ListEventsBefore :many
SELECT seq, type, time, data, source_event_seqs, surface_op, ignorable
FROM events
WHERE session_id = ? AND seq < ?
ORDER BY seq DESC
LIMIT ?
`

type ListEventsBeforeParams struct {
	SessionID string
	Seq       int64
	Limit     int64
}

type ListEventsBeforeRow struct {
	Seq             int64
	Type            string
	Time            int64
	Data            string
	SourceEventSeqs sql.NullString
	SurfaceOp       sql.NullString
	Ignorable       sql.NullInt64
}

func (q *Queries) ListEventsBefore(ctx context.Context, arg ListEventsBeforeParams) ([]ListEventsBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBefore, arg.SessionID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsBeforeRow{}
	for rows.Next() {
		var i ListEventsBeforeRow
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.Time,
			&i.Data,
			&i.SourceEventSeqs,
			&i.SurfaceOp,
			&i.Ignorable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsFrom = `-- name: ListEventsFrom :many
SELECT seq, type, time, data, source_event_seqs, surface_op, ignorable
FROM events
WHERE session_id = ? AND seq >= ?
ORDER BY seq
LIMIT ?
`

type ListEventsFromParams struct {
	SessionID string
	Seq       int64
	Limit     int64
}

type ListEventsFromRow struct {
	Seq             int64
	Type            string
	Time            int64
	Data            string
	SourceEventSeqs sql.NullString
	SurfaceOp       sql.NullString
	Ignorable       sql.NullInt64
}

func (q *Queries) ListEventsFrom(ctx context.Context, arg ListEventsFromParams) ([]ListEventsFromRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsFrom, arg.SessionID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsFromRow{}
	for rows.Next() {
		var i ListEventsFromRow
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.Time,
			&i.Data,
			&i.SourceEventSeqs,
			&i.SurfaceOp,
			&i.Ignorable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestEvents = `-- name: ListLatestEvents :many
SELECT seq, type, time, data, source_event_seqs, surface_op, ignorable
FROM events
WHERE session_id = ?
ORDER BY seq DESC
LIMIT ?
`

type ListLatestEventsParams struct {
	SessionID string
	Limit     int64
}

type ListLatestEventsRow struct {
	Seq             int64
	Type            string
	Time            int64
	Data            string
	SourceEventSeqs sql.NullString
	SurfaceOp       sql.NullString
	Ignorable       sql.NullInt64
}

func (q *Queries) ListLatestEvents(ctx context.Context, arg ListLatestEventsParams) ([]ListLatestEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestEvents, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestEventsRow{}
	for rows.Next() {
		var i ListLatestEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.Time,
			&i.Data,
			&i.SourceEventSeqs,
			&i.SurfaceOp,
			&i.Ignorable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSessions = `-- name: ListLatestSessions :many
SELECT id, version, created_at, cwd, parent_session, seed_length, origin,
       delegation_depth, agent_preset, incarnation, revision
FROM sessions
ORDER BY created_at DESC, id ASC
LIMIT ?1
`

func (q *Queries) ListLatestSessions(ctx context.Context, queryLimit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSessions, queryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.Cwd,
			&i.ParentSession,
			&i.SeedLength,
			&i.Origin,
			&i.DelegationDepth,
			&i.AgentPreset,
			&i.Incarnation,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsAfter = `-- name: ListSessionsAfter :many
SELECT id, version, created_at, cwd, parent_session, seed_length, origin,
       delegation_depth, agent_preset, incarnation, revision
FROM sessions
WHERE created_at < ?1
   OR (created_at = ?1 AND id > ?2)
ORDER BY created_at DESC, id ASC
LIMIT ?3
`

type ListSessionsAfterParams struct {
	CursorCreatedAt int64
	CursorID        string
	QueryLimit      int64
}

func (q *Queries) ListSessionsAfter(ctx context.Context, arg ListSessionsAfterParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsAfter, arg.CursorCreatedAt, arg.CursorID, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.Cwd,
			&i.ParentSession,
			&i.SeedLength,
			&i.Origin,
			&i.DelegationDepth,
			&i.AgentPreset,
			&i.Incarnation,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
