// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbsql

import (
	"context"
)

const definitionRevision = `-- name: DefinitionRevision :one
SELECT revision
FROM bound_definitions
WHERE name = ?
`

func (q *Queries) DefinitionRevision(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, definitionRevision, name)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const insertDefinition = `-- name: InsertDefinition :execrows
INSERT INTO bound_definitions (
    name,
    revision,
    definition_json
) VALUES (?, ?, ?)
ON CONFLICT(name) DO NOTHING
`

type InsertDefinitionParams struct {
	Name           string
	Revision       int64
	DefinitionJson []byte
}

func (q *Queries) InsertDefinition(ctx context.Context, arg InsertDefinitionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDefinition, arg.Name, arg.Revision, arg.DefinitionJson)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDefinitions = `-- name: ListDefinitions :many
SELECT name, revision, definition_json
FROM bound_definitions
ORDER BY name
`

func (q *Queries) ListDefinitions(ctx context.Context) ([]BoundDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoundDefinition{}
	for rows.Next() {
		var i BoundDefinition
		if err := rows.Scan(&i.Name, &i.Revision, &i.DefinitionJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceDefinition = `-- name: ReplaceDefinition :execrows
UPDATE bound_definitions
SET
    revision = ?,
    definition_json = ?
WHERE name = ? AND revision = ?
`

type ReplaceDefinitionParams struct {
	Revision       int64
	DefinitionJson []byte
	Name           string
	Revision_2     int64
}

func (q *Queries) ReplaceDefinition(ctx context.Context, arg ReplaceDefinitionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceDefinition,
		arg.Revision,
		arg.DefinitionJson,
		arg.Name,
		arg.Revision_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
