// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

import (
	"database/sql"
)

type Event struct {
	SessionID       string
	Seq             int64
	Type            string
	Time            int64
	Data            string
	SourceEventSeqs sql.NullString
	SurfaceOp       sql.NullString
	Ignorable       sql.NullInt64
}

type PersistenceState struct {
	Singleton int64
	StoreID   string
}

type Session struct {
	ID              string
	Version         int64
	CreatedAt       int64
	Cwd             sql.NullString
	ParentSession   sql.NullString
	SeedLength      sql.NullInt64
	Origin          sql.NullString
	DelegationDepth sql.NullInt64
	AgentPreset     sql.NullString
	Incarnation     string
	Revision        int64
}
