// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsql

type Workspace struct {
	ID         string
	Path       string
	Title      string
	SessionIds string
	CreatedAt  string
	UpdatedAt  string
}

type WorkspaceState struct {
	Singleton          int64
	Initialized        int64
	WorkspaceIds       string
	ArchivedSessionIds string
}
