// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbsql

import (
	"context"
)

const deleteAllWorkspaces = `-- name: DeleteAllWorkspaces :exec
DELETE FROM workspaces
`

func (q *Queries) DeleteAllWorkspaces(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllWorkspaces)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWorkspaceState = `-- name: GetWorkspaceState :one
SELECT initialized, workspace_ids, archived_session_ids
FROM workspace_state
WHERE singleton = 1
`

type GetWorkspaceStateRow struct {
	Initialized        int64
	WorkspaceIds       string
	ArchivedSessionIds string
}

func (q *Queries) GetWorkspaceState(ctx context.Context) (GetWorkspaceStateRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceState)
	var i GetWorkspaceStateRow
	err := row.Scan(&i.Initialized, &i.WorkspaceIds, &i.ArchivedSessionIds)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspaces (id, path, title, session_ids, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertWorkspaceParams struct {
	ID         string
	Path       string
	Title      string
	SessionIds string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspace,
		arg.ID,
		arg.Path,
		arg.Title,
		arg.SessionIds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, path, title, session_ids, created_at, updated_at
FROM workspaces
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Title,
			&i.SessionIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putWorkspaceState = `-- name: PutWorkspaceState :exec
INSERT INTO workspace_state (singleton, initialized, workspace_ids, archived_session_ids)
VALUES (1, ?, ?, ?)
ON CONFLICT(singleton) DO UPDATE SET
    initialized = excluded.initialized,
    workspace_ids = excluded.workspace_ids,
    archived_session_ids = excluded.archived_session_ids
`

type PutWorkspaceStateParams struct {
	Initialized        int64
	WorkspaceIds       string
	ArchivedSessionIds string
}

func (q *Queries) PutWorkspaceState(ctx context.Context, arg PutWorkspaceStateParams) error {
	_, err := q.db.ExecContext(ctx, putWorkspaceState, arg.Initialized, arg.WorkspaceIds, arg.ArchivedSessionIds)
	return err
}

const setArchivedSessionIDs = `-- name: SetArchivedSessionIDs :execrows
UPDATE workspace_state SET archived_session_ids = ? WHERE singleton = 1
`

func (q *Queries) SetArchivedSessionIDs(ctx context.Context, archivedSessionIds string) (int64, error) {
	result, err := q.db.ExecContext(ctx, setArchivedSessionIDs, archivedSessionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkspaceOrder = `-- name: SetWorkspaceOrder :execrows
UPDATE workspace_state SET workspace_ids = ? WHERE singleton = 1
`

func (q *Queries) SetWorkspaceOrder(ctx context.Context, workspaceIds string) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWorkspaceOrder, workspaceIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspace = `-- name: UpdateWorkspace :execrows
UPDATE workspaces SET
    path = ?,
    title = ?,
    session_ids = ?,
    created_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Path       string
	Title      string
	SessionIds string
	CreatedAt  string
	UpdatedAt  string
	ID         string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspace,
		arg.Path,
		arg.Title,
		arg.SessionIds,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
